#!/bin/bash
# Demo script showing usage of the tropical cyclone tracking tools
# This demonstrates the commands without running full model inference

echo "=========================================================================="
echo "Tropical Cyclone Tracking Tools - Usage Demonstration"
echo "=========================================================================="
echo ""

echo "1. Regional Model Utilities - Display available domains"
echo "----------------------------------------------------------------------"
echo "Command: python scripts/regional_model_utils.py"
echo ""
python scripts/regional_model_utils.py
echo ""

echo "=========================================================================="
echo "2. Example Commands (not executed in this demo)"
echo "=========================================================================="
echo ""

echo "Track cyclones using GFS data and SFNO model:"
echo "  python scripts/tc_tracker_india.py \\"
echo "    --data-source GFS \\"
echo "    --model SFNO \\"
echo "    --nsteps 20 \\"
echo "    --output-dir outputs/cyclone_tracks"
echo ""

echo "Track cyclones using ERA5 data and DLWP model:"
echo "  python scripts/tc_tracker_india.py \\"
echo "    --data-source ERA5 \\"
echo "    --model DLWP \\"
echo "    --nsteps 30 \\"
echo "    --output-dir outputs/historical_cyclones"
echo ""

echo "Regional cyclone evaluation with example cyclones:"
echo "  python scripts/regional_cyclone_eval.py \\"
echo "    --region north_indian_ocean \\"
echo "    --data-source GFS \\"
echo "    --model SFNO \\"
echo "    --nsteps 20"
echo ""

echo "Regional cyclone evaluation with custom cyclone list:"
echo "  python scripts/regional_cyclone_eval.py \\"
echo "    --region bay_of_bengal \\"
echo "    --cyclones example_cyclones.json \\"
echo "    --nsteps 25"
echo ""

echo "=========================================================================="
echo "3. Example Cyclone List Format"
echo "=========================================================================="
echo ""
echo "File: example_cyclones.json"
cat example_cyclones.json
echo ""

echo "=========================================================================="
echo "4. Available Regional Domains"
echo "=========================================================================="
echo ""
echo "Domain IDs for --region parameter:"
echo "  - india_full           : Full Indian Subcontinent"
echo "  - north_indian_ocean   : Arabian Sea and Bay of Bengal"
echo "  - bay_of_bengal        : Bay of Bengal cyclone region"
echo "  - arabian_sea          : Arabian Sea cyclone region"
echo "  - india_monsoon        : Indian monsoon region"
echo ""

echo "=========================================================================="
echo "5. Documentation"
echo "=========================================================================="
echo ""
echo "For detailed documentation, see: docs/CYCLONE_TRACKING.md"
echo ""
echo "The documentation includes:"
echo "  - Comprehensive usage guide"
echo "  - Command-line argument reference"
echo "  - Regional domain descriptions"
echo "  - Data source information (GFS vs ERA5)"
echo "  - Model comparisons (SFNO, DLWP, FCN)"
echo "  - Output format specifications"
echo "  - Multiple usage examples"
echo ""

echo "=========================================================================="
echo "Demo Complete!"
echo "=========================================================================="
